[package]
name = "dcmget-dicom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
dicom-core.workspace = true
dicom-dictionary-std = { workspace = true, features = ["sop-class"] }
dicom-encoding.workspace = true
dicom-object.workspace = true
dicom-transfer-syntax-registry.workspace = true
dicom-ul.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
